### ISSUE TITLE
maximum number of iterations Exceeded

### ISSUE THREAD

**Issue by YuWVandy** [jump-dev/Ipopt.jl#218] opened 2020-07-31 13:32 UTC
Hi guys,
 I've been using IPOPT in Julia to solve a nonlinear optimization problem. When I change the following equality constraint to the inequality constraint, the optimization iteration always exceeds the maximum number. And I have changed the maximum number from default 3000 to 100000 but it still doesn't work. Does anyone know the possible reason causing such things?

Originally the constraint is:
    @NLconstraint(mp, Glinkprflow[i = 1:length(Gflow)], Gflow[i]^(1/dt.delta5) == 13.9867*(Gpr[Glist2adj[i, 1]]^2 - Gpr[Glist2adj[i, 2]]^2)/(Gasdistnode2node[Glist2adj[i, 1], Glist2adj[i, 2]]))
And I transform into:
    @NLconstraint(mp, Glinkprflow[i = 1:length(Gflow)], Gflow[i]^(1/dt.delta5) <= 13.9867*(Gpr[Glist2adj[i, 1]]^2 - Gpr[Glist2adj[i, 2]]^2)/(Gasdistnode2node[Glist2adj[i, 1], Glist2adj[i, 2]]))
The decision variables are  Gflow and Gpr, which are all greater than 0 (greater or equal to pretty small value).
Some of the optimization results is also posted below:
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
2950r 1.3136628e+05 1.16e+02 1.70e+06  -0.2 3.58e-01   3.6 1.00e+00 8.21e-02f  1
2951r 1.3135239e+05 1.17e+02 1.71e+06  -0.2 1.03e+00   3.1 1.00e+00 1.11e-01f  1
2952r 1.3134971e+05 1.17e+02 3.25e+06  -0.2 2.55e+00   2.6 1.00e+00 7.60e-03f  1
2953r 1.3128442e+05 1.17e+02 2.91e+06  -0.2 1.90e+01   2.2 1.30e-01 6.71e-02f  1
2954r 1.3126592e+05 1.17e+02 2.19e+06  -0.2 3.44e+00   2.6 1.00e+00 5.43e-02f  1
2955r 1.3123992e+05 1.17e+02 2.12e+06  -0.2 1.41e+01   2.1 4.83e-02 2.78e-02f  1
2956r 1.3118141e+05 1.17e+02 3.45e+06  -0.2 3.22e+00   2.5 1.00e+00 1.64e-01f  1
2957r 1.3117184e+05 1.17e+02 2.97e+06  -0.2 4.71e+01   2.0 8.31e-02 1.02e-02f  1
2958r 1.3111838e+05 1.18e+02 3.00e+06  -0.2 3.63e+00   2.5 1.00e+00 1.40e-01f  1
2959r 1.3110225e+05 1.18e+02 2.47e+06  -0.2 1.70e-01   3.8 2.85e-02 8.36e-01f  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
2960r 1.3110175e+05 1.18e+02 2.36e+06  -0.2 4.91e-01   4.2 2.68e-02 7.16e-02f  1
2961r 1.3110173e+05 1.18e+02 2.21e+06  -0.2 3.37e-01   4.7 5.86e-02 9.95e-03f  1
2962r 1.3110135e+05 1.18e+02 2.27e+06  -0.2 4.16e-02   5.1 2.27e-01 3.69e-01f  1
2963r 1.3110097e+05 1.18e+02 5.47e+06  -0.2 3.49e-02   5.5 1.49e-01 1.00e+00f  1
2964r 1.3109970e+05 1.18e+02 3.44e+05  -0.2 3.18e-02   5.0 9.65e-01 9.55e-01f  1
2965r 1.3109696e+05 1.18e+02 5.40e+05  -0.2 2.99e-02   4.6 1.00e+00 7.08e-01f  1
2966r 1.3109418e+05 1.18e+02 8.28e+05  -0.2 8.98e-02   4.1 1.00e+00 2.57e-01f  1
2967r 1.3108660e+05 1.18e+02 6.24e+05  -0.2 2.70e-01   3.6 2.70e-01 2.50e-01f  1
2968r 1.3108140e+05 1.18e+02 5.30e+05  -0.2 1.01e-01   4.0 1.00e+00 4.59e-01f  1
2969r 1.3107673e+05 1.18e+02 4.31e+05  -0.2 3.01e-01   3.5 2.84e-01 1.42e-01f  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
2970r 1.3107197e+05 1.18e+02 3.49e+05  -0.2 8.99e-01   3.1 4.24e-01 5.06e-02f  1
2971r 1.3106811e+05 1.18e+02 3.25e+05  -0.2 3.37e-01   3.5 1.00e+00 1.09e-01f  1
2972r 1.3104483e+05 1.18e+02 3.38e+05  -0.2 1.01e+00   3.0 1.00e+00 2.23e-01f  1
2973r 1.3103331e+05 1.18e+02 8.07e+05  -0.2 5.53e+00   2.5 1.00e+00 3.82e-02f  1
2974r 1.3099986e+05 1.18e+02 8.97e+05  -0.2 1.18e+00   3.0 1.00e+00 2.93e-01f  1
2975r 1.3098493e+05 1.18e+02 2.05e+06  -0.2 2.10e+01   2.5 5.36e-01 4.23e-02f  1
2976r 1.3092959e+05 1.19e+02 1.10e+06  -0.2 2.94e+00   2.9 1.00e+00 4.14e-01f  1
2977r 1.3092298e+05 1.19e+02 8.62e+05  -0.2 4.83e-01   3.3 3.24e-01 1.39e-01f  1
2978r 1.3091994e+05 1.19e+02 7.16e+05  -0.2 1.79e-01   3.8 3.74e-01 1.57e-01f  1
2979r 1.3090423e+05 1.19e+02 5.74e+05  -0.2 1.22e+00   3.3 2.08e-01 2.48e-01f  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
2980r 1.3090047e+05 1.19e+02 5.61e+05  -0.2 3.47e+00   2.8 2.19e-02 2.03e-02f  1
2981r 1.3089729e+05 1.19e+02 8.77e+05  -0.2 6.07e-01   3.2 1.00e+00 5.08e-02f  1
2982r 1.3088017e+05 1.19e+02 1.10e+06  -0.2 1.83e+00   2.8 2.50e-01 9.41e-02f  1
2983r 1.3085582e+05 1.19e+02 5.13e+06  -0.2 5.54e+00   2.3 1.00e+00 4.79e-02f  1
2984r 1.3082349e+05 1.19e+02 6.40e+06  -0.2 1.68e+01   1.8 1.00e+00 2.57e-02f  1
2985r 1.3069853e+05 1.20e+02 6.35e+06  -0.2 5.22e+01   1.3 1.00e+00 4.91e-02f  1
2986r 1.3047790e+05 1.22e+02 6.81e+06  -0.2 2.88e+02   0.9 1.44e-01 2.40e-02f  1
2987r 1.3033836e+05 1.23e+02 8.10e+06  -0.2 6.16e+01   1.3 4.94e-01 6.19e-02f  1
2988r 1.3000655e+05 1.25e+02 8.23e+06  -0.2 1.70e+04   0.8 1.94e-03 4.15e-04f  1
2989r 1.2988357e+05 1.26e+02 8.46e+06  -0.2 8.85e+01   1.2 3.26e-01 4.23e-02f  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
2990r 1.2980780e+05 1.26e+02 8.11e+06  -0.2 2.54e+01   1.7 9.50e-01 1.05e-01f  1
2991r 1.2975278e+05 1.27e+02 5.94e+06  -0.2 8.56e+00   2.1 1.00e+00 2.02e-01f  1
2992r 1.2963297e+05 1.28e+02 5.99e+06  -0.2 2.61e+01   1.6 3.55e-01 8.49e-02f  1
2993r 1.2960998e+05 1.28e+02 5.82e+06  -0.2 7.67e+01   1.1 3.53e-01 7.28e-02f  1
2994r 1.2956058e+05 1.28e+02 5.83e+06  -0.2 2.32e+02   0.7 1.67e-01 1.62e-02f  1
2995r 1.2951262e+05 1.28e+02 5.89e+06  -0.2 7.11e+02   0.2 1.99e-01 1.31e-02f  1
2996r 1.2948548e+05 1.28e+02 5.88e+06  -0.2 2.62e+02   0.6 3.98e-01 1.88e-02f  1
2997r 1.2944783e+05 1.27e+02 5.83e+06  -0.2 8.85e+02   0.1 2.72e-01 1.97e-02f  1
2998r 1.2946968e+05 1.25e+02 5.51e+06  -0.2 3.04e+02   0.5 1.00e+00 6.13e-02f  1
2999r 1.2932283e+05 1.17e+02 5.35e+06  -0.2 1.31e+03   0.1 7.83e-02 2.98e-02f  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
3000r 1.2933500e+05 1.15e+02 5.30e+06  -0.2 4.28e+02   0.5 1.00e+00 1.94e-02f  1

Number of Iterations....: 3000

                                   (scaled)                 (unscaled)
Objective...............:   1.2933500341296638e+05    1.2933500341296638e+05
Dual infeasibility......:   5.2956146479914347e+06    5.2956146479914347e+06
Constraint violation....:   1.1483608559451601e+02    1.1483608559451601e+02
Complementarity.........:   7.5090119199254298e+02    7.5090119199254298e+02
Overall NLP error.......:   4.8911970032064064e+03    5.2956146479914347e+06

Number of objective function evaluations             = 5366
Number of objective gradient evaluations             = 2185
Number of equality constraint evaluations            = 18148
Number of inequality constraint evaluations          = 18148
Number of equality constraint Jacobian evaluations   = 3028
Number of inequality constraint Jacobian evaluations = 3028
Number of Lagrangian Hessian evaluations             = 3000
Total CPU secs in IPOPT (w/o function evaluations)   =     34.555
Total CPU secs in NLP function evaluations           =     13.186

EXIT: Maximum Number of Iterations Exceeded.

**Comment by odow** [comment] 2020-07-31 16:50
Please post user questions like this on the Discourse: https://discourse.julialang.org/c/domain/opt/13.

In addition, read the first post of https://discourse.julialang.org/t/psa-make-it-easier-to-help-you/14757/81 and provide a minimal working example; you probably didn't see the iteration limit correctly.

**Comment by odow** [comment] 2020-10-27 02:48
Closing because this is not a bug in Ipopt.jl:

Here is how to set the iteration limit:
```Julia
using JuMP, Ipopt
model = Model(Ipopt.Optimizer)
set_optimizer_attribute(model, "max_iter", 1)
@variable(model, x)
@NLobjective(model, Min, abs(x))
julia> optimize!(model)
This is Ipopt version 3.13.2, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        1

Total number of variables............................:        1
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  0.0000000e+00 0.00e+00 1.00e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  1.0000000e+04 0.00e+00 1.00e+00  -1.7 1.00e+04  -4.0 1.00e+00 1.00e+00S1076

Number of Iterations....: 1

                                   (scaled)                 (unscaled)
Objective...............:   1.0000000000000000e+04    1.0000000000000000e+04
Dual infeasibility......:   1.0000000000000000e+00    1.0000000000000000e+00
Constraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   0.0000000000000000e+00    0.0000000000000000e+00
Overall NLP error.......:   1.0000000000000000e+00    1.0000000000000000e+00


Number of objective function evaluations             = 1081
Number of objective gradient evaluations             = 2
Number of equality constraint evaluations            = 0
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 0
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 1
Total CPU secs in IPOPT (w/o function evaluations)   =      0.017
Total CPU secs in NLP function evaluations           =      0.001

EXIT: Maximum Number of Iterations Exceeded.

julia> termination_status(model)
ITERATION_LIMIT::TerminationStatusCode = 11
```

**Closed by odow** 2020-10-27 02:48 UTC
