### ISSUE TITLE
Update Ipopt does not update

### ISSUE THREAD

**Issue by stumarcus314** [jump-dev/Ipopt.jl#411] opened 2024-05-31 16:38 UTC
My version of Ipopt.jl is v1.5.1, even though v1.6.2 is available. When I try to update Ipopt in the package manager, there is no change or update.

pkg> status
Status `~/.julia/environments/v1.10/Project.toml`
...
⌃ [b6b21f68] Ipopt v1.5.1
...
Info Packages marked with ⌃ have new versions available and may be upgradable.

pkg> update Ipopt
    Updating registry at `~/.julia/registries/General.toml`
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`

**Comment by odow** [comment] 2024-05-31 19:21
Then you have another package blocking it.

Do `] add Ipopt@1.6.2` to find the issue.

**Comment by stumarcus314** [comment] 2024-05-31 19:54
I followed your advice. It looks like SCIP.jl was downgraded from v0.11.14 to v0.11.6, in order to upgrade Ipopt.jl from v1.5.1 to 1.6.2.

(@v1.10) pkg> status
Status `~/.julia/environments/v1.10/Project.toml`
  [07493b3f] Alpine v0.5.6
  [7c4d4715] AmplNLWriter v1.2.1
  [227a2e2d] COPT v1.1.17
  [bb8be931] EAGO v0.8.1
  [7a1cc6ca] FFTW v1.8.0
  [87dc4568] HiGHS v1.9.0
⌅ [d1acc4aa] IntervalArithmetic v0.20.9
⌃ [b6b21f68] Ipopt v1.5.1
  [4076af6c] JuMP v1.22.1
  [2ddba703] Juniper v0.9.2
  [19f71287] MAiNGO v0.2.2
  [33e6dc65] MKL v0.6.3
  [82193955] SCIP v0.11.14
  [29cba6d7] Bonmin_jll v100.800.901+0
  [f09e9e23] Couenne_jll v0.500.801+0
Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated`

(@v1.10) pkg> add Ipopt@1.6.2
   Resolving package versions...
   Installed MUMPS_seq_jll ────── v500.600.201+0
   Installed SPRAL_jll ────────── v2024.1.18+0
   Installed NNlib ────────────── v0.7.6
   Installed Ipopt_jll ────────── v300.1400.1400+0
   Installed TranscodingStreams ─ v0.10.9
   Installed McCormick ────────── v0.13.4
   Installed SCIP_jll ─────────── v0.2.1+0
   Installed Ipopt ────────────── v1.6.2
   Installed SCIP_PaPILO_jll ──── v0.1.0+3
   Installed SCIP ─────────────── v0.11.6
  Downloaded artifact: MUMPS_seq
  Downloaded artifact: SPRAL
  Downloaded artifact: Ipopt
  Downloaded artifact: SCIP
  Downloaded artifact: SCIP_PaPILO
    Updating `~/.julia/environments/v1.10/Project.toml`
  [b6b21f68] ↑ Ipopt v1.5.1 ⇒ v1.6.2
⌃ [82193955] ↓ SCIP v0.11.14 ⇒ v0.11.6
    Updating `~/.julia/environments/v1.10/Manifest.toml`
  [79e6a3ab] - Adapt v3.7.2
  [a9b6321e] - Atomix v0.1.0
  [fa961155] - CEnum v0.5.0
  [d360d2e6] - ChainRulesCore v1.23.0
  [46192b85] - GPUArraysCore v0.1.5
  [b6b21f68] ↑ Ipopt v1.5.1 ⇒ v1.6.2
  [63c18a36] - KernelAbstractions v0.9.19
  [929cbde3] - LLVM v7.1.0
⌃ [53c679d3] ↓ McCormick v0.13.6 ⇒ v0.13.4
⌅ [872c559c] ↓ NNlib v0.8.21 ⇒ v0.7.6
⌃ [82193955] ↓ SCIP v0.11.14 ⇒ v0.11.6
  [3bb67fe8] ↑ TranscodingStreams v0.10.8 ⇒ v0.10.9
  [013be700] - UnsafeAtomics v0.2.1
  [d80eeb9a] - UnsafeAtomicsLLVM v0.1.4
  [9cc047cb] ↑ Ipopt_jll v300.1400.1302+0 ⇒ v300.1400.1400+0
  [dad2f222] - LLVMExtra_jll v0.0.29+0
  [d7ed1dd3] ↑ MUMPS_seq_jll v500.600.100+0 ⇒ v500.600.201+0
⌅ [fc9abe76] ↓ SCIP_PaPILO_jll v800.100.0+0 ⇒ v0.1.0+3
⌅ [e5ac4fe4] ↓ SCIP_jll v800.100.0+1 ⇒ v0.2.1+0
  [319450e9] ↑ SPRAL_jll v2023.8.2+0 ⇒ v2024.1.18+0
⌅ [28df3c45] ↓ boost_jll v1.79.0+0 ⇒ v1.76.0+1
        Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated -m`
    Building SCIP → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/ac0512c46cd91744f62463514f2c581025ea5b93/build.log`
Precompiling project...
  30 dependencies successfully precompiled in 302 seconds. 82 already precompiled.
  1 dependency had output during precompilation:
┌ McCormick
│  WARNING: method definition for mm_kernel at /home/stuart/.julia/packages/McCormick/1T0df/src/forward_operators/other.jl:681 declares type variable T but does not use it.
│  WARNING: method definition for mm_kernel at /home/stuart/.julia/packages/McCormick/1T0df/src/forward_operators/other.jl:681 declares type variable N but does not use it.
│  WARNING: method definition for gen_expansion_params! at /home/stuart/.julia/packages/McCormick/1T0df/src/implicit_routines/implicit.jl:274 declares type variable T but does not use it.
│  WARNING: method definition for gen_expansion_params! at /home/stuart/.julia/packages/McCormick/1T0df/src/implicit_routines/implicit.jl:274 declares type variable N but does not use it.
│  WARNING: method definition for implicit_relax_h! at /home/stuart/.julia/packages/McCormick/1T0df/src/implicit_routines/implicit.jl:296 declares type variable T but does not use it.
│  WARNING: method definition for implicit_relax_h! at /home/stuart/.julia/packages/McCormick/1T0df/src/implicit_routines/implicit.jl:296 declares type variable N but does not use it.
└

(@v1.10) pkg> status
Status `~/.julia/environments/v1.10/Project.toml`
  [07493b3f] Alpine v0.5.6
  [7c4d4715] AmplNLWriter v1.2.1
  [227a2e2d] COPT v1.1.17
  [bb8be931] EAGO v0.8.1
  [7a1cc6ca] FFTW v1.8.0
  [87dc4568] HiGHS v1.9.0
⌅ [d1acc4aa] IntervalArithmetic v0.20.9
  [b6b21f68] Ipopt v1.6.2
  [4076af6c] JuMP v1.22.1
  [2ddba703] Juniper v0.9.2
  [19f71287] MAiNGO v0.2.2
  [33e6dc65] MKL v0.6.3
⌃ [82193955] SCIP v0.11.6
  [29cba6d7] Bonmin_jll v100.800.901+0
  [f09e9e23] Couenne_jll v0.500.801+0
Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated`

**Comment by odow** [comment] 2024-05-31 20:04
A bunch of other packages changed too.

In a fresh project I can install both Ipopt@1.6.2 and SCIP@0.11.14.
```Julia
(ip) pkg> st
Status `/private/tmp/ip/Project.toml`
  [b6b21f68] Ipopt v1.6.2
  [82193955] SCIP v0.11.14
```

I don't know what the underlying conflict is, but you have a bunch of other packages involved that could be contributing. I would encourage you to use a new environment for each project, and keep only the minimum number of required packages in each environment.

This is not a bug in Ipopt.

**Comment by stumarcus314** [comment] 2024-05-31 20:15
Would "pkg> add SCIP@0.11.14" revert my packages back to the way they were before updating to Ipopt v1.6.2?

**Comment by odow** [comment] 2024-05-31 20:19
I don't know.

The package manager tries to pick a compatible set of versions for the packages you install.

In some cases, there can be multiple solutions that are Pareto optimal (updating package A requires an older version of package B, and vice versa).

You likely can't install the latest version of Ipopt AND SCIP AND some other package (perhaps IntervalArithmetic) at the same time.

There is no control over which Pareto point the package manager will find. The only real tool (other than manually specifying compat bounds in `Project.toml`) is that you can specify specific versions with `@x.y.x`.

**Comment by odow** [comment] 2024-06-03 22:13
Closing because this is not a bug in Ipopt. There must be something in your environment other than Ipopt and SCIP that is leading to this behavior.

**Closed by odow** 2024-06-03 22:13 UTC
