### ISSUE TITLE
Error linking IPOPT with HSL built on Windows

### ISSUE THREAD

**Issue by ueliwechsler** [jump-dev/Ipopt.jl#229] opened 2020-11-03 15:55 UTC
Following the [instruction]( https://coin-or.github.io/Ipopt/INSTALL.html) to build `Ipopt.jl` onWindows (see more details below), I wanted to run `Ipopt.jl` with the custom binaries.

But running `Pkg.build("Ipopt")` failes at https://github.com/jump-dev/Ipopt.jl/blob/a7231ce420a7616cd51278f7196b94037a41c91c/deps/build.jl#L118
with the error message
```julia
┌ Error: Error building `Ipopt`:
│ ERROR: LoadError: Could not install custom libraries from D:/Libraries/msys64/mingw64/bin and D:/Libraries/msys64/mingw64/lib.
│ To fall back to BinaryProvider call delete!(ENV,"JULIA_IPOPT_LIBRARY_PATH");delete!(ENV,"JULIA_IPOPT_EXECUTABLE_PATH") and run build
again.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at D:\Libraries\Julia\v1.x\packages\Ipopt\bYzBL\deps\build.jl:122
│  [3] include(::String) at .\client.jl:457
│  [4] top-level scope at none:5
│ in expression starting at D:\Libraries\Julia\v1.x\packages\Ipopt\bYzBL\deps\build.jl:116
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Operations.jl:949
```

I am a bit lost at the moment. Any pointers on how to proceed? Did I miss something?

One problem that I noticed is that if a run `Libdl.dlopen("D:/Libraries/msys64/mingw64/bin/libipopt-3.dll")`,it kills the Julia session  most of the time . Except if I do it with Julia 1.3.1 then I get 
```julia
julia> Libdl.dlopen("D:/Libraries/msys64/mingw64/bin/libipopt-3.dll")
Ptr{Nothing} @0x0000000065180000
```

<details>
  <summary>Installation procedure:</summary>

###  Install [msys2](https://www.msys2.org/)
1. `pacman -Syu`
2. `pacman -Su`
3. Install required dependencies
     - `pacman -S binutils diffutils git grep make patch pkg-config`
     - `pacman -S mingw-w64-x86_64-gcc`
     - `pacman -S mingw-w64-x86_64-gfortran` 
        => did not work, replaced by `pacman -S gcc-fortran`
     - `pacman -S mingw-w64-x86_64-lapack mingw-w64-x86_64-metis`
4. Install other dependencies (might not be needed)
   - `pacman -S mingw-w64-x86_64-gcc`
   - `pacman -S mingw-w64-x86_64-toolchain `
   - `pacman -S autoconf make libtool automake git`

### open `Mingw-w64 64 bit`
1. `cd D:/Libraries/Ipopt_msys2`

### ASL  
1. `git clone https://github.com/coin-or-tools/ThirdParty-ASL.git`
2. `cd ThirdParty-ASL`
3. `./get.ASL` # adds solvers
3. `./configure`
4. `make`
5. `make install`
6. `cd ..`
### HSL
1. `git clone https://github.com/coin-or-tools/ThirdParty-HSL.git`
2. `cd ThirdParty-HSL`
2.  add the `coinhsl` folder
3. `./configure`
4. `make`
5. `make install`
6. `cd ..`

  ### Ipopt 
1. `git clone https://github.com/coin-or/Ipopt.git`
8. `cd Ipopt`
6. `mkdir build`
5. `cd build`
4. `../configure`
    - `checking for package HSL... yes`
    - `checking for package ASL... yes`
3. `make`
    * libtool: warning: 'D:/Libraries/msys64/mingw64/lib/libcoinhsl.la' seems to be moved
    * libtool: warning: '-version-info' is ignored for programs
2. `make test`
    *  Test passed!
1. `make install`

### Ipopt.jl
```julia
ENV["JULIA_IPOPT_LIBRARY_PATH"] = "D:/Libraries/msys64/mingw64/bin"
ENV["JULIA_IPOPT_EXECUTABLE_PATH"] = "D:/Libraries/msys64/mingw64/lib"
import Pkg; Pkg.build("Ipopt")
Ipopt → `D:\Libraries\Julia\v1.x\packages\Ipopt\bYzBL\deps\build.log`
┌ Error: Error building `Ipopt`:
│ ERROR: LoadError: Could not install custom libraries from  and .
│ To fall back to BinaryProvider call delete!(ENV,"JULIA_IPOPT_LIBRARY_PATH");delete!(ENV,"JULIA_IPOPT_EXECUTABLE_PATH") and run build
again.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at D:\Libraries\Julia\v1.x\packages\Ipopt\bYzBL\deps\build.jl:122
│  [3] include(::String) at .\client.jl:457
│  [4] top-level scope at none:5
│ in expression starting at D:\Libraries\Julia\v1.x\packages\Ipopt\bYzBL\deps\build.jl:116
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Operations.jl:949
```
</details>

<details>
  <summary>File Structure</summary>

- `D:\Libraries\msys64\mingw64\bin`
![image](https://user-images.githubusercontent.com/12156892/98006812-f8e54c00-1df2-11eb-9319-05d53bb98cba.png)
- `D:\Libraries\msys64\mingw64\lib`
![image](https://user-images.githubusercontent.com/12156892/98006896-0dc1df80-1df3-11eb-9230-951a2bb2b03e.png)

</details>

<details>
  <summary>System specifications</summary>

```julia
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake-avx512)
```
</details>

Thanks for any help in advance!

Side note: This compilation was done because I want to use the ma27 solver with `Ipopt.jl`

**Comment by odow** [comment] 2020-11-03 18:31
Related: https://github.com/jump-dev/Ipopt.jl/issues/192. I don't have experience running Ipopt with HSL on Windows. Is it an issue that it's called `libipopt-3.dll` instead of `libipopt.dll`?

**Comment by ueliwechsler** [comment] 2020-11-03 20:51
> Is it an issue that it's called `libipopt-3.dll` instead of `libipopt.dll`?

Hi odow, I don't think so. I changed the name of the dll to `libipopt.dll` instead and the error persists. One problem is that I am not sure if it is a problem with the compiled Ipopt executables or the linking with Julia.
I see #192 before but I am not sure if it is really related since the main issue there is administrative privileges.

**Comment by ViralBShah** [comment] 2020-11-04 16:35
Can you share your entire build recipe and such? Does one need the HSL license to try and build this?

@staticfloat may have more insights.

**Comment by ViralBShah** [comment] 2020-11-04 16:40
Given that HSL is source available, we could build it as part of Yggdrasil as part of the default Ipopt. Of course commercial users have to ensure they have a license.

**Comment by ViralBShah** [comment] 2020-11-04 16:42
@dpo Anything you know or can share? Also pinging @staticfloat here.

**Comment by staticfloat** [comment] 2020-11-04 16:49
@ueliwechsler what versions of `gcc` and `fortran` did you build with?  You can tell with `gcc --version` and `gfortran --version`.  I'd like to see if that version matches up with what Julia is expecting.  Could you post the output of `using Pkg.BinaryPlatforms; triplet(platform_key_abi())`?

**Comment by dpo** [comment] 2020-11-04 18:26
@ViralBShah Are you sure it's ok to precompile the HSL sources? One needs to fill out a form to obtain them. They're not open source. They're just available for research purposes. That said, a recipe could probably be written based on https://github.com/JuliaSmoothOptimizers/HSL.jl/blob/master/deps/build.jl but I've never tried on Windows, and again, I'm doubtful that it's legit to ship binaries.

**Comment by ViralBShah** [comment] 2020-11-04 20:20
@dpo Thanks. I see the licensing here now: http://www.hsl.rl.ac.uk/licencing.html 

I originally wondered whether we could distribute the libraries, but they would not be usable without a license. Looking at the licencing page, it is clear that distribution is not possible.

**Comment by ueliwechsler** [comment] 2020-11-05 08:19
@staticfloat: The versions of `gcc` and `fortran` are:
```
$ gcc --version
gcc.exe (Rev4, Built by MSYS2 project) 10.2.0
$ gfortran --version
GNU Fortran (Rev4, Built by MSYS2 project) 10.2.0
```
and 
```
julia> using Pkg.BinaryPlatforms; triplet(platform_key_abi())
"x86_64-w64-mingw32-libgfortran5-cxx11"
```

**Comment by staticfloat** [comment] 2020-11-05 19:50
Hmmm, that looks good actually.  Okay so then we're going to have to dig into why things are crashing.  Can you install `gdb` (I'm not sure what system you're using to install `gcc`, but the same way you do that likely will allow you to install `gdb`) then run Julia inside of `gdb` (run `gdb julia`, then use the `c` command at the `(gdb)` prompt to "continue" program execution) and load the .DLL that is causing it to crash?

Once it crashes, you should drop back down into a `(gdb)` prompt again, at which point you can get a backtrace with the `bt` command.  That will hopefully tell us precisely where things are crashing.

**Comment by ueliwechsler** [comment] 2020-11-05 22:44
I think I fixed the problem with the crashing. 
I did repeat the entire build process with `Mingw-w64 64 bit` 
On `Julia 1.5.2` and  now calling `Libdl.dlopen("D:/Libraries/msys64/mingw64/bin/libipopt-3.dll")`
returns `Ptr{Nothing} @0x0000000065180000` without crashing.
The only explanation that I can think of is that the last time I did build `Ipopt`, I was using `Mingw-w64 32 bit` instead of the 64 bit version which caused the crashing.

So this is already progress :) I couldn't make `gdb` work so far but I assume this is not needed anymore.

Now, when running 
```julia
ENV["JULIA_IPOPT_LIBRARY_PATH"] = raw"D:\Libraries\msys64\mingw64\bin"
ENV["JULIA_IPOPT_EXECUTABLE_PATH"] = raw"D:\Libraries\msys64\mingw64\lib"
import Pkg; Pkg.build("Ipopt"; verbose=true)
```
I still get the same error. 
```julia
   Building Ipopt → `D:\Libraries\Julia\v1.x\packages\Ipopt\bYzBL\deps\build.log`
ERROR: LoadError: Could not install custom libraries from D:\Libraries\msys64\mingw64\bin and D:\Libraries\msys64\mingw64\lib.
To fall back to BinaryProvider call delete!(ENV,"JULIA_IPOPT_LIBRARY_PATH");delete!(ENV,"JULIA_IPOPT_EXECUTABLE_PATH") and run build again.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at D:\Libraries\Julia\v1.x\packages\Ipopt\bYzBL\deps\build.jl:122
 [3] include(::String) at .\client.jl:457
 [4] top-level scope at none:5
in expression starting at D:\Libraries\Julia\v1.x\packages\Ipopt\bYzBL\deps\build.jl:116
┌ Error: Error building `Ipopt`:
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Operations.jl:949
```
However, if I set `ENV["JULIA_IPOPT_EXECUTABLE_PATH"] = raw"D:\Libraries\msys64\mingw64\bin"` the `build.jl` file runs without error.
So in my in my case the library-path and the executable-path are the same, right?

Now if I run the example file `hs071.jl` with the option `addOption(prob, "linear_solver", "ma27")`  I get the following error message.
```julia
Exception of type: OPTION_INVALID in file "IpAlgBuilder.cpp" at line 268:
 Exception message: Selected linear solver MA27 not available.
Tried to obtain MA27 from shared library "libhsl.so", but the following error occured:
loadLib error: Do not know how to handle shared libraries on this operating system
EXIT: Invalid option encountered.
```
This is the point where I am stuck at the moment. I am not sure if this is a problem with the HSL library, the ipopt or the naming.
The HSL library is called `libcoinhsl-2.dll`. Do I have to change this and if so, at what point of the built?

Thanks a lot!

**Comment by ViralBShah** [comment] 2020-11-05 22:50
Is there any possibility of trying this out on a linux system to see if it works there - to isolate if the problem is windows specific or across the board?

**Comment by ueliwechsler** [comment] 2020-11-05 23:18
I have no option to test it on a similar system with Linux operating system at the moment.  But as far as I know, this should work well on Linux and the HSL source files are available upon request from their webpage.

**Comment by staticfloat** [comment] 2020-11-06 01:31
> The only explanation that I can think of is that the last time I did build Ipopt, I was using Mingw-w64 32 bit instead of the 64 bit version which caused the crashing.

This is plausible. :)

> So in my in my case the library-path and the executable-path are the same, right?

On windows, DLLs (which are shared libraries) are placed within `bin` instead of `lib`, so I think this makes sense.

> Therefore, I am not sure if the build was successful.

I'm pretty sure something is screwed up in your build.  For one thing, it's trying to load a `.so` file, which is a Linux file extension.  For another, that error message (`loadLib error: Do not know how to handle shared libraries on this operating system`) seems to be associated with Ipopt [not knowing it's running on Windows](https://list.coin-or.org/pipermail/ipopt/2013-August/003480.html).

You may want to try cleaning and re-configuring the ipopt build with an explicit build triplet, e.g. `./configure --build=x86_64-w64-mingw32 [other configure args]`.  If you do that, feel free to post the output here as well so I can take a quick look at that (and maybe the first couple lines of you compiling it) to see if anything stands out.  So far, you've done an excellent job of including output, thank you for that.

**Comment by ueliwechsler** [comment] 2020-11-06 22:28
> You may want to try cleaning and re-configuring the ipopt build with an explicit build triplet, e.g. `./configure --build=x86_64-w64-mingw32 [other configure args]`

Thanks, I will give it a try and come back to you with the outputs.

**Comment by ueliwechsler** [comment] 2020-11-10 17:59
Finally, I made it work! 

The final problem had nothing to do with the `Ipopt` built. 

It's really silly. I always set the environmental variables in the Julia code as `ENV["JULIA_IPOPT_LIBRARY_PATH"] = raw"D:\Libraries\msys64\mingw64\bin", ...` instead of just setting them globally. Therefore, when running `using Ipopt` in a new `Julia` session, the line
https://github.com/jump-dev/Ipopt.jl/blob/d9e9176620a9b527a08991a3d41062fa948867f7/src/Ipopt.jl#L5
returned `false`and it fell back to using `Ipopt_jll` instead of considering the `deps.jl` file 🤦‍♂️.

To sum up, I was quite close from the beginning and the following points helped me fix it:
- with `msys2` use `Mingw-w64 64-bit` not the ~`32-bit version`~
- Set both environmental variables  `JULIA_IPOPT_EXECUTABLE_PATH` and `JULIA_IPOPT_LIBRARY_PATH` to `D:\Libraries\msys64\mingw64\bin` (the `bin` directory of `mingw64` of the `msys2` installation) instead of the `lib` directory for the `LIBRARY_PATH` (also set it globally)
- follow the build recipe from [my first post](https://github.com/jump-dev/Ipopt.jl/issues/229#issue-735438164)

Thanks a lot for your support!

**Comment by odow** [comment] 2020-11-18 23:52
I'm updating (in #236) the build instructions for a custom installation: https://github.com/jump-dev/Ipopt.jl/tree/od/pardiso#custom-installation 
Let me know if they could be improved.

**Comment by ViralBShah** [comment] 2020-11-19 00:27
Can we make many of these solvers available through Yggdrasil in a default build configuration? So that users can switch at runtime? I'll be happy to help with adding more.

**Comment by odow** [comment] 2020-11-19 00:30
I don't think so. HSL is off the cards (https://github.com/jump-dev/Ipopt.jl/issues/229#issuecomment-721954043), and Pardiso (https://www.pardiso-project.org) has a similar license.

**Comment by ViralBShah** [comment] 2020-11-19 00:38
LAPACK is already provided in OpenBLAS. Why do we need to do this?

**Comment by ueliwechsler** [comment] 2020-11-19 07:30
> I'm updating (in #236) the build instructions for a custom installation: https://github.com/jump-dev/Ipopt.jl/tree/od/pardiso#custom-installation
> Let me know if they could be improved.

Thanks, the changes you made include my "lessons learned", so I have nothing to add there. I'll add a section for the HSL solver suit on Windows once I have made `ma86` and `ma97` work on my system.

**Comment by odow** [comment] 2020-11-23 03:21
Closing since #236 how has much improved instructions for custom installations. #247 can track adding HSL support on Windows.

**Closed by odow** 2020-11-23 03:21 UTC
Labels: Custom build
