### ISSUE TITLE
Issue with non-negative variable tolerance.

### ISSUE THREAD

**Issue by mariaepinheiro** [jump-dev/Ipopt.jl#362] opened 2023-05-25 10:50 UTC
I am using IPOPT to solve an optimization problem.

One of my variables must satisfy 0 \leq x \leq 1. But the problem gives a solution of -1e-7, which cannot happen, Is it possible to put some command so that the tolerance of the feasible point is smaller (1e-9 for example)?

**Comment by odow** [comment] 2023-05-28 23:57
Closing because this is not a bug in Ipopt.

If you have any questions related to Ipopt and tolerances, please post on the community forum, https://discourse.julialang.org/c/domain/opt/13, and we can discuss further.

**Closed by odow** 2023-05-28 23:57 UTC
