### ISSUE TITLE
Cannot be installed properly on Alpine Linux which is a MUSL based distro

### ISSUE THREAD

**Issue by DoctorDro** [jump-dev/Ipopt.jl#402] opened 2024-01-30 16:03 UTC
Dear all,
trying to install PowerModels and Ipopt on Latest Julia 10 under Alpine Linux failed because Ipopt cannot be installed there. Ipopt fails due to shared libraries such as libmetis.so cannot be loaded. 
```
ERROR: LoadError: InitError: could not load library "/home/Dr2Dr/.julia/artifacts/056dc52f41656651083a0a7a46b9d87e9ada7ff9/lib/libcmumps.so"
Error loading shared library libmetis.so: No such file or directory (needed by /home/Dr2Dr/.julia/artifacts/056dc52f41656651083a0a7a46b9d87e9ada7ff9/lib/libcmumps.so)
```
Trying to create symbolic links where Ipopt expects libmetis.so revealed that other libraries such as spral dependencies could not be found due to the same reason. Then creating again symbolic links revealed that other libraries such as libipoptamplinterface.so could not be loaded and so on ...

Any ideas why that could be happening only on musl linux systems and not on any other Windows, Linux or FreeBSD?

**Comment by odow** [comment] 2024-01-30 19:03
What is the output of `] st -m`?

Do earlier versions of Ipopt install?

**Comment by odow** [comment] 2024-01-30 19:48
> Earlier versions of Ipopt do not install

But the 1.5.1 version installed in https://github.com/jump-dev/Ipopt.jl/issues/403?

What is `versioninfo()`? How did you install Julia?

**Comment by odow** [comment] 2024-01-30 19:58
Does it work on Julia 1.9 or earlier?

**Comment by odow** [comment] 2024-01-30 20:51
> What is versioninfo()

?

> I cannot install all Julia versions and test them
> Alpine Linux can be installed on Windows by the Microsoft Store with one click.

I don't have a Windows machine, so I can't reproduce this. It'd be helpful if you could.

I'll also note that MUSL is Tier 2 support: https://julialang.org/downloads/

"Tier 2: Julia is guaranteed to build from source using the default build options, but may or may not pass all tests. Official binaries are available on a case-by-case basis."

I'll talk to some folks on slack, but I don't really have any ideas or suggestions for how to go about debugging this.

**Comment by odow** [comment] 2024-01-30 21:02
Upstream issue is: https://github.com/JuliaLang/julia/issues/40556#issuecomment-825126303

The recommendation is either to not use MUSL, or to apply Julian's patch: https://github.com/JuliaLang/julia/issues/40556#issuecomment-825126303

Here's the conversation from slack for posterity:
![image](https://github.com/jump-dev/Ipopt.jl/assets/8177701/2d7eec47-6d63-4d70-af8f-fd68021ef47c)

Closing because there doesn't seem to be anything we can do from the perspective of Ipopt.jl.

**Closed by odow** 2024-01-30 21:02 UTC
