### ISSUE TITLE
exception_access_violation and julia exits

### ISSUE THREAD

**Issue by MartaVanin** [jump-dev/Ipopt.jl#220] opened 2020-08-27 09:40 UTC
Hello,
I apologize for not providing reproducible code, but the issue I bumped into has occurred only running a few instances of a package which is currently not available, and it's a bit tricky to provide some smaller example atm. 
I hope you can still point me into some direction I can look into to fix this.
The problem I am trying to solve is a non-convex optimal power flow-like problem, and julia exited after returning the error below. For other input data examples in the same format the code works fine. From the last line of the error I would think that it has to do with memory, but the failing data inputs are not necessarily those of the largest problem examples, so I am not sure what could cause this.

I use:
Windows 10 Pro
Ipopt 3.13.2 with mumps
I tried both Ipopt.jl v0.6.2 and v0.6.3
I tried both julia v1.4.2 and 1.5.1 

`Exception: EXCEPTION_ACCESS_VIOLATION at 0x417a93d8 -- mumps_cst_amf_ at C:\Users\mvanin\.julia\artifacts\85636c56ff20059d466f2c530b801398692be07f\bin\libmumps_common.dll (unknown line)
in expression starting at C:\Users\mvanin\.julia\dev\PowerModelsDSSE\scripts\validate_reduced_form.jl:58
mumps_cst_amf_ at C:\Users\mvanin\.julia\artifacts\85636c56ff20059d466f2c530b801398692be07f\bin\libmumps_common.dll (unknown line)
__dmumps_ana_aux_m_MOD_dmumps_ana_f at C:\Users\mvanin\.julia\artifacts\85636c56ff20059d466f2c530b801398692be07f\bin\libdmumps.dll (unknown line)
dmumps_ana_driver_ at C:\Users\mvanin\.julia\artifacts\85636c56ff20059d466f2c530b801398692be07f\bin\libdmumps.dll (unknown line)
dmumps_ at C:\Users\mvanin\.julia\artifacts\85636c56ff20059d466f2c530b801398692be07f\bin\libdmumps.dll (unknown line)
.text at C:\Users\mvanin\.julia\artifacts\85636c56ff20059d466f2c530b801398692be07f\bin\libdmumps.dll (unknown line)
dmumps_c at C:\Users\mvanin\.julia\artifacts\85636c56ff20059d466f2c530b801398692be07f\bin\libdmumps.dll (unknown line)
_ZN5Ipopt20MumpsSolverInterface21SymbolicFactorizationEv at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
_ZN5Ipopt20MumpsSolverInterface10MultiSolveEbPKiS2_iPdbi at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
_ZN5Ipopt16TSymLinearSolver10MultiSolveERKNS_9SymMatrixERSt6vectorINS_8SmartPtrIKNS_6VectorEEESaIS8_EERS4_INS5_IS6_EESaISC_EEbi at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
_ZN5Ipopt18StdAugSystemSolver10MultiSolveEPKNS_9SymMatrixEdPKNS_6VectorEdS6_dPKNS_6MatrixES6_dS9_S6_dRSt6vectorINS_8SmartPtrIS5_EESaISC_EESF_SF_SF_RSA_INSB_IS4_EESaISG_EESJ_SJ_SJ_bi at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
_ZN5Ipopt15AugSystemSolver5SolveEPKNS_9SymMatrixEdPKNS_6VectorEdS6_dPKNS_6MatrixES6_dS9_S6_dRS5_SA_SA_SA_RS4_SB_SB_SB_bi at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
_ZN5Ipopt22LeastSquareMultipliers20CalculateMultipliersERNS_6VectorES2_ at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
_ZN5Ipopt25DefaultIterateInitializer18least_square_multsERKNS_10JournalistERNS_8IpoptNLPERNS_9IpoptDataERNS_25IpoptCalculatedQuantitiesERKNS_8SmartPtrINS_22EqMultiplierCalculatorEEEd at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
_ZN5Ipopt25DefaultIterateInitializer18SetInitialIteratesEv at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
_ZN5Ipopt14IpoptAlgorithm18InitializeIteratesEv at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
_ZN5Ipopt14IpoptAlgorithm8OptimizeEb at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
_ZN5Ipopt16IpoptApplication13call_optimizeEv at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
_ZN5Ipopt16IpoptApplication11OptimizeNLPERKNS_8SmartPtrINS_3NLPEEERNS1_INS_16AlgorithmBuilderEEE at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
_ZN5Ipopt16IpoptApplication11OptimizeNLPERKNS_8SmartPtrINS_3NLPEEE at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
_ZN5Ipopt16IpoptApplication12OptimizeTNLPERKNS_8SmartPtrINS_4TNLPEEE at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
IpoptSolve at C:\Users\mvanin\.julia\artifacts\9bbae3ca1bc91c80de275f8ccbbb3baea4f1d148\bin\libipopt-3.dll (unknown line)
solveProblem at C:\Users\mvanin\.julia\packages\Ipopt\YJcu4\src\Ipopt.jl:361
optimize! at C:\Users\mvanin\.julia\packages\Ipopt\YJcu4\src\MOI_wrapper.jl:914
optimize! at C:\Users\mvanin\.julia\packages\MathOptInterface\bygN7\src\Bridges\bridge_optimizer.jl:239
optimize! at C:\Users\mvanin\.julia\packages\MathOptInterface\bygN7\src\Utilities\cachingoptimizer.jl:189
#optimize!#95 at C:\Users\mvanin\.julia\packages\JuMP\MnJQc\src\optimizer_interface.jl:131
optimize! at C:\Users\mvanin\.julia\packages\JuMP\MnJQc\src\optimizer_interface.jl:107 [inlined]
optimize! at C:\Users\mvanin\.julia\packages\JuMP\MnJQc\src\optimizer_interface.jl:107 [inlined]
macro expansion at .\util.jl:308 [inlined]
#optimize_model!#19 at C:\Users\mvanin\.julia\packages\InfrastructureModels\BdnLM\src\core\base.jl:232
optimize_model!##kw at C:\Users\mvanin\.julia\packages\InfrastructureModels\BdnLM\src\core\base.jl:218
#run_model#219 at C:\Users\mvanin\.julia\packages\PowerModels\72tBz\src\core\base.jl:49
unknown function (ip: 0000000061E5BA3F)
run_model##kw at C:\Users\mvanin\.julia\packages\PowerModels\72tBz\src\core\base.jl:32
#run_mc_model#1271 at C:\Users\mvanin\.julia\packages\PowerModelsDistribution\8FyCU\src\prob\common.jl:10
unknown function (ip: 0000000061E5B526)
run_mc_model at C:\Users\mvanin\.julia\packages\PowerModelsDistribution\8FyCU\src\prob\common.jl:3
#run_mc_se#189 at C:\Users\mvanin\.julia\dev\PowerModelsDSSE\src\prob\se.jl:50
run_mc_se at C:\Users\mvanin\.julia\dev\PowerModelsDSSE\src\prob\se.jl:44 [inlined]
#run_acp_red_mc_se#186 at C:\Users\mvanin\.julia\dev\PowerModelsDSSE\src\prob\se.jl:23 [inlined]
run_acp_red_mc_se at C:\Users\mvanin\.julia\dev\PowerModelsDSSE\src\prob\se.jl:23
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1700 [inlined]
do_call at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:369
eval_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:458
eval_stmt_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:409 [inlined]
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:799
jl_interpret_toplevel_thunk at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:911
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:819
jl_parse_eval_all at /cygdrive/d/buildbot/worker/package_win64/build/src\ast.c:872
include_string at .\loading.jl:1080
include_string at C:\Users\mvanin\.julia\packages\CodeTools\VsjEq\src\eval.jl:30
unknown function (ip: 000000001BC13C79)
#202 at C:\Users\mvanin\.julia\packages\Atom\ipSjf\src\eval.jl:119
withpath at C:\Users\mvanin\.julia\packages\CodeTools\VsjEq\src\utils.jl:30
withpath at C:\Users\mvanin\.julia\packages\Atom\ipSjf\src\eval.jl:9
#201 at C:\Users\mvanin\.julia\packages\Atom\ipSjf\src\eval.jl:118 [inlined]
with_logstate at .\logging.jl:398
with_logger at .\logging.jl:505 [inlined]
#200 at C:\Users\mvanin\.julia\packages\Atom\ipSjf\src\eval.jl:117 [inlined]
hideprompt at C:\Users\mvanin\.julia\packages\Atom\ipSjf\src\repl.jl:127
macro expansion at C:\Users\mvanin\.julia\packages\Atom\ipSjf\src\eval.jl:116 [inlined]
macro expansion at C:\Users\mvanin\.julia\packages\Media\ItEPc\src\dynamic.jl:24 [inlined]
eval at C:\Users\mvanin\.julia\packages\Atom\ipSjf\src\eval.jl:113
unknown function (ip: 0000000000F7ABD3)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1700 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:643
jl_f__apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:657 [inlined]
jl_f__apply_latest at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:693
#invokelatest#1 at .\essentials.jl:712
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1700 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:643
invokelatest at .\essentials.jl:711
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1700 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:643
macro expansion at C:\Users\mvanin\.julia\packages\Atom\ipSjf\src\eval.jl:41 [inlined]
#184 at .\task.jl:358
unknown function (ip: 000000001BB3BD33)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1700 [inlined]
start_task at /cygdrive/d/buildbot/worker/package_win64/build/src\task.c:687
Allocations: 471417539 (Pool: 471323454; Big: 94085); GC: 252`

**Comment by odow** [comment] 2020-08-27 19:47
I don't think there is much we can do without an example.

**Comment by odow** [comment] 2020-10-27 02:43
Closing because this is not reproducible. Please reopen if you can find a reproducible test case.

**Closed by odow** 2020-10-27 02:43 UTC
