### ISSUE TITLE
Dual Sign Changes Explanations

### ISSUE THREAD

**Issue by andrewrosemberg** [jump-dev/Ipopt.jl#431] opened 2024-08-30 15:31 UTC
We are trying to understand the dual sign changes in the Ipopt wrapper.

I.e., How the dual multiplier
https://github.com/jump-dev/Ipopt.jl/blob/4c156461ef1fda3c9f015520197afda4e8ca3e26/src/MOI_wrapper.jl#L1325

is used depending on each constraint / bound type: e.g., 
https://github.com/jump-dev/Ipopt.jl/blob/4c156461ef1fda3c9f015520197afda4e8ca3e26/src/MOI_wrapper.jl#L1340

Can we have some line comments for each case explaining the reasoning?

**Comment by odow** [comment] 2024-08-31 02:54
All `MOI.AbstractOptimizer`s implement the same dual convention: https://jump.dev/MathOptInterface.jl/stable/background/duality/

 * The dual of a `>=` (`MOI.GreaterThan` / `MOI.Nonnegatives`) constraint is non-negative, because the dual cone of `MOI.Nonnegatives` is `MOI.Nonnegatives`.
 * The dual of a `<=` (`MOI.LessThan` / `MOI.Nonpositives`) constraint is non-positive, because the dual cone of `MOI.Nonpositives` is `MOI.Nonpositives`
 * The dual of a `==` constraint is free, and the sign depends on which "side" of the equality is binding (see two points above)

It has been a while since I needed to remember the details of Ipopt, but from memory, the dual of the constraint rows (`.mult_g`) had the opposite convention to the variable bounds (`.mult_x_L` and `.mult_x_U`)?

I remember it being confusing.

**Comment by odow** [comment] 2024-09-01 21:30
Closing because this is not a bug in Ipopt. (But please comment if you have an example of a bug where the above doesn't hold.)

**Closed by odow** 2024-09-01 21:30 UTC
