### ISSUE TITLE
Ipopt throws errors that seem memory relevant

### ISSUE THREAD

**Issue by wzhangw** [jump-dev/Ipopt.jl#244] opened 2020-11-22 23:02 UTC
I am running the following toy model using Ipopt v0.6.3 and JuMP v0.21.5 in Julia 1.5.3 (OS is Ubuntu 18.04) and see various errors thrown out

```
using JuMP, Ipopt

m = Model(Ipopt.Optimizer);

@variable(m, x[1:2] >= 0);
@constraint(m, x[1] + x[2] <= 5)
@objective(m, Max, 2*x[1] + 3*x[2]) 

optimize!(m)
```

Different error messages appear when I run the same model multiple times. I post a few of them below as examples. The errors seem to be related to memory allocation?
```
julia> include("./ipopt_example.jl")

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.13.2, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

corrupted double-linked list

signal (6): Aborted
in expression starting at /home/wzhang483/ipopt_example.jl:16
^C^Z
[1]+  Stopped                 ./julia/julia-1.5.3/bin/julia
```

```
julia> include("./ipopt_example.jl")

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.13.2, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

julia: malloc.c:3830: _int_malloc: Assertion `chunk_main_arena (bck->bk)' failed.

signal (6): Aborted
in expression starting at /home/wzhang483/ipopt_example.jl:16
^Z
[2]+  Stopped                 ./julia/julia-1.5.3/bin/julia
```

```
julia> include("./ipopt_example.jl")

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.13.2, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

corrupted size vs. prev_size

signal (6): Aborted
in expression starting at /home/wzhang483/ipopt_example.jl:16
```

In each case above Julia gets stuck so I pause the process manually.

**Comment by odow** [comment] 2020-11-22 23:26
Probable duplicate of #242

**Comment by odow** [comment] 2020-11-23 01:32
This should be fixed now. Run `] up`, then start a new Julia session for the changes to take effect.

**Comment by wzhangw** [comment] 2020-11-23 03:35
Is this supposed to pin MUMPS to v5.2.1 as mentioned in #246 ? I tried to run `] up` but it's still `MUMPS_seq_jll v5.3.5` in `Manifest.toml`. I ended up getting Ipopt work normally by pinning `MUMPS_seq_jll` manually.

**Comment by odow** [comment] 2020-11-23 03:57
Running `] up` should upgrade `Ipopt_jll`. Just un-install Ipopt and re-install:
```
] rm Ipopt
] rm MUMPS_seq_jll
] up
] add Ipopt
```

Closing since this was a duplicate of #242

**Closed by odow** 2020-11-23 03:57 UTC
