### ISSUE TITLE
Wrong result for Ackleys Function

### ISSUE THREAD

**Issue by ChrisNabold** [jump-dev/Ipopt.jl#222] opened 2020-09-29 14:58 UTC
I tried to solve the 2d-Ackleys function using Ipopt. Whereas both Gams(with Conopt) and KNITRO gives the correct result x[1]=x[2]=0 and objective_value=40.  Ipopt results in x[1]=x[2] and objective_value=0.
```Julia
using JuMP, Ipopt
m = Model(Ipopt.Optimizer)
@variable(m, x[1:2])
@NLobjective(m, Min,  20*exp(-0.2*sqrt((x[1]^2 + x[2]^2)/2)) -
             exp((cos(2*pi*x[1]) + cos(2*pi*x[2]))/2) + 20 + exp(1))
optimize!(m)
value.(x[1])
value.(x[2])
objective_value(m)
```

**Comment by odow** [comment] 2020-09-29 23:01
Use `termination_status(m)` and `primal_status(m)` to check the solution before querying it. In this case, Ipopt did not complete successfully:
```Julia
julia> optimize!(m)
This is Ipopt version 3.13.2, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        3

Total number of variables............................:        2
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0


Number of Iterations....: 0

Number of objective function evaluations             = 0
Number of objective gradient evaluations             = 1
Number of equality constraint evaluations            = 0
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 0
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 0
Total CPU secs in IPOPT (w/o function evaluations)   =      0.000
Total CPU secs in NLP function evaluations           =      0.000

EXIT: Invalid number in NLP function or derivative detected.

julia> termination_status(m)
INVALID_MODEL::TerminationStatusCode = 21

julia> primal_status(m)
UNKNOWN_RESULT_STATUS::ResultStatusCode = 8
```
Ipopt assumes the function is twice-differentiable, which is not satisfied at x=0 due to `sqrt(0.0)`.

**Comment by odow** [comment] 2020-09-30 01:49
Closing since this is expected behavior. 

Please post on the forum if you have further questions: https://discourse.julialang.org/c/domain/opt/13

**Closed by odow** 2020-09-30 01:49 UTC
